### ISSUE TITLE
YAML Syntax Error: Duplicated mapping key

### ISSUE THREAD

**Issue by jukey** [zalando/innkeeper#150]
The [Swagger editor](http://editor.swagger.io/) complains regarding the Syntax in the [YAML file](https://github.com/zalando/innkeeper/blob/master/swagger.yaml):

```YAML
 YAML Syntax Error
Duplicated mapping key at line 437, column 3: RouteChange: ^
Jump to line 436
Details
 Object
 yamlError: n(t,e){Error.call(this),Error.captureStackTrace?Error.captureStackTrace(this,this.constructor):this.stack=(new Error).stack||"",this.name="YAMLException",this.reason=t,this.mark=e,this.message=(this.reason||"(unknown reason)")+(this.mark?" "+this.mark.toString
level: 900
type:  "YAML Syntax Error"
description:  "Duplicated mapping key at line 437, column 3:
      RouteChange:
      ^"
lineNumber: 436
```
